# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["rauf@guliyev.net"]
description = "Connect to an identity provider such as Google using OAuth 2.0 and validate authentication status at the Edge, to authorize access to your edge or origin hosted applications."
language = "go"
manifest_version = 3
name = "compute-go-auth"
service_id = "QUKtqfyS3w6jejH0XLIqm0"

[local_server]

  [local_server.backends]

    [local_server.backends.idp]
      url = "https://accounts.google.com/"

    [local_server.backends.origin]
      url = "https://httpbin.org/"

  [local_server.config_stores]

    [local_server.config_stores.oauth_config]
      format = "inline-toml"

      [local_server.config_stores.oauth_config.contents]
        callback_path = "/callback"
        code_challenge_method = "S256"
        introspect_access_token = "true"
        jwks = "{\"keys\":[{\"n\":\"z_M5h3XCzegfOG7jFYGWUIuwjaZ5-RE_cFhjzduahNJpv_sEBD_K6ZuarVTAfYP_5ff6nUBkFyu1DZ7pZiNJ_rtVfefd_mCUZX6ioLrj0IJNgcW99zg6KZ29IceoO9l601by7akzJj0NIg2I9L30Pw4PcBQuSjKyiuJQT3UJR3ZePENh05HU9CZBY2zMOvG8wBc84J4xKXF8nJNsU-leGYzxR6FauayyB5f6I_nvZDEp9QzGEVFMX0J7VNcZyYUEh2Z7wYWX9ryszD40zXUFbtRT9pND8haUcH_Hdsy2teYlHqtx4IPyL9PDdWcY2H9KN8cYRpPyP3zbZ5CKX0dvTQ\",\"alg\":\"RS256\",\"kty\":\"RSA\",\"e\":\"AQAB\",\"kid\":\"1bb774bd8729ea38e9c2fe0c64d2ca948bf66f0f\",\"use\":\"sig\"},{\"n\":\"woRUr445_ODXrFeynz5L208aJkABOKQHEzbfGM_V1ijkYZWZKY0PXKPP_wRKcE4C6OyjDNd5gHh3dF5QsVhVDZCfR9QjTf94o4asngrHzdOcfQ0pZIvzu_vzaVG82VGLM-2rKQp8uz06A6TbUzbIv9wQ8wQpYDIdujNkLqL22Mkb2drPxm9Y9I05PmVdkkvAbu4Q_KRJWxykOigHp-hVBmpYS2P3xuX56gM7ZRcXXJKKUfrGel4nDhSIAAD1wBNcVVgKbb0TYfZmVpRSCji_b6JHjqYhYjUasdotYJzWl7quAFsN_X_4j-cHZ30OS81j--OiIxWpL11y1kcbE0u-Dw\",\"kty\":\"RSA\",\"use\":\"sig\",\"alg\":\"RS256\",\"e\":\"AQAB\",\"kid\":\"882503a5fd56e9f734dfba5c50d7bf48db284ae9\"}]}"
        jwt_access_token = "false"
        openid_configuration = "{\"issuer\":\"https://accounts.google.com\",\"authorization_endpoint\":\"https://accounts.google.com/o/oauth2/v2/auth\",\"device_authorization_endpoint\":\"https://oauth2.googleapis.com/device/code\",\"token_endpoint\":\"https://oauth2.googleapis.com/token\",\"userinfo_endpoint\":\"https://openidconnect.googleapis.com/v1/userinfo\",\"revocation_endpoint\":\"https://oauth2.googleapis.com/revoke\",\"jwks_uri\":\"https://www.googleapis.com/oauth2/v3/certs\",\"response_types_supported\":[\"code\",\"token\",\"id_token\",\"code token\",\"code id_token\",\"token id_token\",\"code token id_token\",\"none\"],\"subject_types_supported\":[\"public\"],\"id_token_signing_alg_values_supported\":[\"RS256\"],\"scopes_supported\":[\"openid\",\"email\",\"profile\"],\"token_endpoint_auth_methods_supported\":[\"client_secret_post\",\"client_secret_basic\"],\"claims_supported\":[\"aud\",\"email\",\"email_verified\",\"exp\",\"family_name\",\"given_name\",\"iat\",\"iss\",\"name\",\"picture\",\"sub\"],\"code_challenge_methods_supported\":[\"plain\",\"S256\"],\"grant_types_supported\":[\"authorization_code\",\"refresh_token\",\"urn:ietf:params:oauth:grant-type:device_code\",\"urn:ietf:params:oauth:grant-type:jwt-bearer\"]}"
        scope = "openid"

  [local_server.secret_stores]

    [[local_server.secret_stores.oauth_secrets]]
      file = ".secret.client_id"
      key = "client_id"

    [[local_server.secret_stores.oauth_secrets]]
      file = ".secret.nonce_secret"
      key = "nonce_secret"

    [[local_server.secret_stores.oauth_secrets]]
      file = ".secret.client_secret"
      key = "client_secret"

    [[local_server.secret_stores.oauth_secrets]]
      file = ".secret.api_key"
      key = "api_key"

[scripts]
  build = "go build -o bin/main.wasm ."
  env_vars = ["GOARCH=wasm", "GOOS=wasip1"]
  post_init = "go get github.com/fastly/compute-sdk-go@latest"

[setup]

  [setup.backends]

    [setup.backends.idp]
      address = "accounts.google.com"
      description = "Identity provider authorization server"

    [setup.backends.origin]
      address = "httpbin.org"
      description = "Content or application origin"

  [setup.config_stores]

    [setup.config_stores.oauth_config]
      description = "Configuration metadata store"

      [setup.config_stores.oauth_config.items]

        [setup.config_stores.oauth_config.items.callback_path]
          description = "Path for the redirection URI to which OAuth 2.0 responses will be sent."
          value = "/callback"

        [setup.config_stores.oauth_config.items.jwks]
          description = "JSON Web Key Set (JWKS) containing the public keys used to verify the JWT signature. You can find this at the jwks_uri endpoint in the OIDC discovery document."

        [setup.config_stores.oauth_config.items.openid_configuration]
          description = "OpenID Connect (OIDC) discovery document containing OAuth 2.0 endpoints. This is usually obtained from https://YOUR_AUTH_SERVER/.well-known/openid-configuration"

  [setup.secret_stores]

    [setup.secret_stores.oauth_secrets]
      description = "Store for authentication secrets"

      [setup.secret_stores.oauth_secrets.entries]

        [setup.secret_stores.oauth_secrets.entries.client_id]
          description = "OAuth 2.0 client ID valid at the Identity Provider's authorization server."

        [setup.secret_stores.oauth_secrets.entries.client_secret]
          description = "[OPTIONAL] client_secret parameter for certain Identity Providers' (e.g., Google) token endpoint."

        [setup.secret_stores.oauth_secrets.entries.nonce_secret]
          description = "A random secret to verify the OpenID nonce used to mitigate replay attacks."
